name: build

on:
  push:
    branches: "**"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgmp-dev libmpfr-dev libppl-dev libz3-dev
      
    - name: Get sources
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Install Rust components
      run: rustup component add rustc-dev llvm-tools-preview
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: RUST_TEST_THREADS=1 cargo test --verbose
